version: '3.1'
services:
  db:
    platform: linux/x86_64
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: codecamp
    volumes:
      - ./mysql:/var/lib/mysql